name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install CockroachDB
        run: curl https://binaries.cockroachdb.com/cockroach-v21.2.5.linux-amd64.tgz | tar -xz && sudo cp -i cockroach-v21.2.5.linux-amd64/cockroach /usr/local/bin/
      - name: Start CockroachDB
        run: ./build.sh start_cockroachdb
      - name: Run the build
        run: ./build.sh verify
      - name: Stop CockroachDB
        run: ./build.sh stop_cockroachdb
